language: java

jdk:
  - oraclejdk8

install: mvn -DartifactId=pherialize -DgroupId=de.ailis.pherialize -Dversion=1.2.3-SNAPSHOT -Dpackaging=jar -Dfile=lib/pherialize-1.2.3-SNAPSHOT.jar -DgeneratePom=false install:install-file